on:
  workflow_dispatch:
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: fregante/setup-git-user@024bc0b8e177d7e77203b48dab6fb45666854b35 # v2
      - uses: DeterminateSystems/determinate-nix-action@4eea0b33e3d1f02ecfe37cf16e7204c424009606 # v3
        with:
          extra-conf: |
            accept-flake-config = true
            commit-lock-file-summary = chore(deps/nix): update
            log-lines = 200
      - run: nix flake update --commit-lock-file
      - id: unpushed
        run: |
          echo "count=$(git rev-list --count "origin/$GITHUB_REF_NAME..HEAD")" >> "$GITHUB_OUTPUT"
      - if: steps.unpushed.outputs.count != '0'
        id: check
        continue-on-error: true
        run: nix flake check --show-trace
      - if: steps.unpushed.outputs.count != '0' && steps.check.outcome == 'failure'
        run: |
          determinate-nixd fix hashes --auto-apply
          git commit -m "chore(deps/nix): fix hashes" ./pkgs || true
      - if: steps.unpushed.outputs.count != '0' && steps.check.outcome == 'failure'
        run: nix flake check --show-trace
      - if: steps.unpushed.outputs.count != '0'
        run: git push
